name: Weather ETL Pipeline

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run pre-commit
      run: |
        poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}
      CITY_NAMES: lagos,ibadan,kano,accra,abuja,pretoria
      COUNTRY_NAMES: nigeria,ghana,south africa
      FIELDS: name,lat,lon,country,state
      WEATHER_FIELDS_EXCLUDE: minutely,hourly,daily,alerts
      START_DATE_YEAR: "2024"
      END_DATE_YEAR: "2024"
    needs: pre-commit
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run tests
      run: poetry run pytest
